#!/usr/bin/env php

<?php

use function Php\Project\Lvl2\run;

require_once 'vendor/autoload.php';

$doc = /** @lang text */
    <<<DOC

Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]

DOC;

$args = Docopt::handle($doc);

run($args);
